"""Initial migration

Revision ID: 1a8ccc98d66c
Revises: 57daf408a7e9
Create Date: 2025-01-08 12:02:15.094283

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a8ccc98d66c'
down_revision = '57daf408a7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'vendor_register', ['user_id'], ['id'])

    with op.batch_alter_table('product_details', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'vendor_register', ['vendor_id'], ['id'])
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])

    with op.batch_alter_table('vendor_register', schema=None) as batch_op:
        batch_op.drop_index('aadhar_number')
        batch_op.drop_index('account_no')
        batch_op.drop_index('pan_card_number')
        batch_op.drop_index('shop_id')
        batch_op.drop_column('vendor_photo')
        batch_op.drop_column('gst')
        batch_op.drop_column('pan_card_number')
        batch_op.drop_column('shop_id')
        batch_op.drop_column('shop_photo')
        batch_op.drop_column('aadhar_number')
        batch_op.drop_column('ifsc_code')
        batch_op.drop_column('sgo_gps_photo')
        batch_op.drop_column('account_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_no', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('sgo_gps_photo', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('ifsc_code', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('aadhar_number', mysql.VARCHAR(length=15), nullable=True))
        batch_op.add_column(sa.Column('shop_photo', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('shop_id', mysql.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('pan_card_number', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('gst', mysql.VARCHAR(length=15), nullable=True))
        batch_op.add_column(sa.Column('vendor_photo', mysql.VARCHAR(length=255), nullable=True))
        batch_op.create_index('shop_id', ['shop_id'], unique=True)
        batch_op.create_index('pan_card_number', ['pan_card_number'], unique=True)
        batch_op.create_index('account_no', ['account_no'], unique=True)
        batch_op.create_index('aadhar_number', ['aadhar_number'], unique=True)

    with op.batch_alter_table('product_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
